// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rcrpypttlckzvipsyncz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJjcnB5cHR0bGNrenZpcHN5bmN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2OTM4NzMsImV4cCI6MjA3MzI2OTg3M30.tYDgAR5TkYvRPifT6Bi07L0dgWO-NSjyPE6BYzzQpZw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});